### ISSUE TITLE
Possibly wrong splice setting with FILAMENTOVERRIDE

### ISSUE THREAD

**Issue by hviet17** [tomvandeneede/p2pp#174]
I had a print that use input 8,7,6 & 2, other inputs are skipped. Somehow the 1st splice on the print doesn't look like what I had when spice tuning. My relevant settings:
```
;P2PP MATERIAL_DEFAULT_-1_0_1
;P2PP MATERIAL_PLA_PLA_-1_0_1

;P2PP MATERIAL_PLA6_PLA2_-2_3_3
;P2PP MATERIAL_PLA2_PLA6_-2_3_3
```

I think the generated gcode use the fallback value instead of what I defined. I don't know if I'm doing something wrong. Any help would be much appreciated.
![20230910_223203](https://github.com/tomvandeneede/p2pp/assets/13247972/94a76df4-dea8-4c47-9db0-7dd1f387d260)
![20230910_224251](https://github.com/tomvandeneede/p2pp/assets/13247972/ebeb4813-737c-470e-8fa3-08feda09a939)
[.12636.gcode_unprocessed.pp.zip]
Gcode:
(https://github.com/tomvandeneede/p2pp/files/12568585/default.12636.gcode_unprocessed.pp.zip)

**Comment by tomvandeneede** [comment]
Which version of P2PP are you using?

**Comment by hviet17** [comment]
@tomvandeneede I'm using the latest 9.01.05

**Comment by tomvandeneede** [comment]
can you please send me the processed and unprpcessed files so I can take a lookOp 10 sep. 2023 om 17:45 heeft Viet Ho ***@***.***> het volgende geschreven:﻿
I had a print that use input 8,7,6 & 2, other inputs are skipped. Somehow the 1st splice on the print doesn't look like what I had when spice tuning. My relevant settings:
;P2PP MATERIAL_DEFAULT_-1_0_1
;P2PP MATERIAL_PLA_PLA_-1_0_1

;P2PP MATERIAL_PLA6_PLA2_-2_3_3
;P2PP MATERIAL_PLA2_PLA6_-2_3_3

I think the generated gcode use the fallback value instead of what I defined. I don't know if I'm doing something wrong. Any help would be much appreciated.


[.12636.gcode_unprocessed.pp.zip]
Gcode:
(https://github.com/tomvandeneede/p2pp/files/12568585/default.12636.gcode_unprocessed.pp.zip)

**Comment by hviet17** [comment]
@tomvandeneede here're the files
[gcodes.zip](https://github.com/tomvandeneede/p2pp/files/12574949/gcodes.zip)

**Comment by hviet17** [comment]
@tomvandeneede I found the culprit. Turn out FILAMENTOVERRIDE is outdated & I have to use custom filament type in Filament Setting. Thank you for your time.
